version: '3.8'

services:
  nginx-manager:
    image: docker.io/wtation/nginx-manager:latest
    container_name: nginx-manager
    restart: unless-stopped

    # 端口映射 (本地绑定 (127.0.0.1))
    ports:
      - 127.0.0.1:8080:5000    # HTTP端口
      - 127.0.0.1:8444:5001  # HTTPS端口
      - 127.0.0.1:8081:80   # Nginx HTTP端口
      - 127.0.0.1:8444:443  # Nginx HTTPS端口

    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ConnectionStrings__Default=Data Source=/app/data/nginxmanager.db
      - NginxManager__DefaultDataDir=/app/data
      - NginxManager__DefaultNginxDir=/app/nginx-instances
      - NginxManager__DefaultSslDir=/app/ssl
      - NginxManager__DefaultLogDir=/app/logs
      - NginxManager__DefaultWebRootDir=/var/www/html

    volumes:
      - ./my-data/data:/app/data:rw
      - ./my-data/nginx-instances:/app/nginx-instances:rw
      - ./my-data/ssl:/app/ssl:rw
      - ./my-data/logs:/app/logs:rw
      - ./my-data/www:/var/www/html:rw
      - ./my-data/temp:/tmp:rw

    networks:
      - nginx-network

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M

networks:
  nginx-network:
    driver: bridge
